base_url = "https://harish-mm.github.io//"
title = "Harish_mm"
build_search_index = false
generate_feed = true
compile_sass = true
minify_html = true

theme = "apollo"

[markdown]
highlight_code = true
highlight_theme = "ayu-dark"

[extra]
toc = true
use_cdn = false
favicon = "/icon/favicon.png"
theme = "toggle" # light, dark, auto, toggle
mathjax = true
mathjax_dollar_inline_enable = true

menu = [
    { name= "/about", url= "/about", weight= 1 },
    { name = "/posts", url= "/posts", weight= 2 },
    { name= "/projects", url= "/projects", weight= 3 },
]

socials = [
    { name = "twitter", url = "https://twitter.com/MmHarrish", icon = "twitter" },
    { name = "github", url = "https://github.com/harish-mm", icon = "github" },
    { name= "linkedin", url= "https://linkedin.com/in/harish-mm/", icon = "linkedin" }
]

custom_css = []

[extra.analytics]
enabled = true

[extra.analytics.goatcounter]
user = "harishmm"
host = "goatcounter.com"    # default= goatcounter.com

[extra.analytics.umami]
website_id = "43929cd1-1e83...."
host_url = "https://stats.mywebsite.com" # default: https://analytics.eu.umami.is